name: CI/CD with Terraform
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    Branches: 
      - dev 

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -backend=false
        working-directory: ./TerraformEC2
      - name: Checking the files created
        run: ls -la
        working-directory: ./TerraformEC2
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./TerraformEC2
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./TerraformEC2
      
