name: CI/CD with Terraform
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    Branches: 
      - dev 

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        uses: terraform init
        working-directory: ./Terraform EC2
      
